### ISSUE TITLE
Seed particles cause a ticking player and crashes the client

### ISSUE THREAD

**Issue by PancakesBatch** [Kamtheman56/Zelda_Mod#21]
When a large explosion occurs, or multiple in quick succession, it seems the particle causes a client crash.

```
[23:24:43] [Server thread/WARN]: Neruina caught an exception, see below for cause
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.mixinextras$bridge$m_9240_$126(ServerGamePacketListenerImpl.java) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at com.bawnorton.neruina.handler.TickHandler.safelyTickPlayer(TickHandler.java:122) ~[Neruina-2.1.2-forge+1.20.1.jar%23656!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.wrapOperation$cmo000$catchTickingPlayer$notTheCauseOfTickLag(ServerGamePacketListenerImpl.java:4296) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.m_5456_()" because "p_41604_" is null
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:147) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:143) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:127) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at com.kamth.zeldamod.entity.custom.projectile.SeedProjectile.m_7941_(SeedProjectile.java:39) ~[zeldamod-1.2.4.jar%23766!/:1.1]
	at net.minecraft.world.entity.projectile.AbstractArrow.handler$fnm000$pickupAsItem(AbstractArrow.java:4194) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.m_6123_(AbstractArrow.java) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.entity.player.Player.m_36277_(Player.java:560) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:527) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23770!/:?]
```

**Comment by Kamtheman56** [comment]
Forgot to close this! But this should have been fixed quite a few updates ago. If this comes up again please report it
